### ISSUE TITLE
uptime -p flag doesn't exist anymore

### ISSUE THREAD

**Issue by ralsei** [jschx/ufetch#14]
not sure if this is just me

**Comment by jschx** [comment]
Hey, sorry for the extremely late reply. I'm a horrible maintainer. As far as I know, the -p flag only exists on Linux. Looking at the latest Ubuntu manpages, it seems that Linux still supports the -p flag. Are you trying to use it on another OS?

**Comment by ralsei** [comment]
I'm running NixOS 17.09 unstable with the latest coreutils, and it appears the flag was removed

**Comment by ralsei** [comment]
https://git.savannah.gnu.org/cgit/coreutils.git/tree/src/uptime.c#n237

yeah it's not in there anymore

**Comment by jschx** [comment]
Okay, it's fixed in ufetch-nixos since last week. I'll do some more research and see what else is affected.

**Comment by jschx** [comment]
I haven't received any reports of problems with other distros, so I'm going to go ahead and close this.
