### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [jschx/ufetch#2]
I'm sure that systemd is not my WM, I don't even have it installed. Please fix.

![ufetch](https://cloud.githubusercontent.com/assets/9256366/7161344/f141851c-e38e-11e4-9294-508247d6980f.png)

**Comment by jschx** [comment]
What distro are you running?

**Comment by ghost** [comment]
crux

**Comment by jschx** [comment]
Okay, what's your xinitrc look like? What is your /bin/sh? What init are you using?

Also try the latest version. Probably won't fix anything here but it's improved.

**Comment by ghost** [comment]
cat: .xinitrc: No such file or directory
I'm using OpenRC. My /bin/sh is bash in posix mode.

**Comment by jschx** [comment]
Well, for the WM to show you have to launch it from the xinitrc. There's not really a simple way to do it without using the xinitrc (look at screenfetch's WM detection).

Do you have all of core installed? A couple of the programs (hostname and uptime) are from packages in core that seem to be missing here, unless bash in POSIX mode is doing some weird stuff.

**Comment by ghost** [comment]
No, I have no .xinitrc. My sessions are in /usr/share/xsessions.
Also, there's no guarantee that the second (or any specific) line of .xinitrc is the window manager. Fix your script.

**Comment by jschx** [comment]
I'm going to go ahead and close this, as nobody else has reported similar issues.
