### ISSUE TITLE
Environmental variables instead of xinitrc

### ISSUE THREAD

**Issue by mehalter** [jschx/ufetch#22]
Is there a reason you are using .xinitrc instead of the `$DESKTOP_SESSION` or `$XDG_CURRENT_DESKTOP` environment variables? I don't use `.xinitrc`, so the current configuration doesn't run on my machine. Mostly just wondering why you chose to parse through since echoing an environmental variable seems easier. (Also, I'm not sure how widely used those two environmental variables are and if they are usually set, could be your reasoning)

**Comment by jschx** [comment]
I could have it check those two before $WM, which is what I intended for people to set if they don’t have an xinitrc.

If it were to check for them, it would display something like “WM: KDE”, which is not really technically accurate, as KDE’s window manager is actually called KWin.

Translating the DE reported by the variables to the WM used in the DE would introduce a level of complexity I’m not really willing to add. I try to not hardcode anything I don’t have to.

Anyone else have an opinion?

**Comment by mehalter** [comment]
Oh you right, I completely wasn't paying attention when I saw WM, I was thinking DE. Sorry!

**Comment by jschx** [comment]
Added checks for $XDG_CURRENT_DESKTOP and $DESKTOP_SESSION in 84edb060eead44480364af13169db8c4310bf6c2. Thanks for the heads up.
