### ISSUE TITLE
Arch logo is a man who plays with his genitals

### ISSUE THREAD

**Issue by wowse** [jschx/ufetch#9]
Arch logo is man who plays with his genitals, I think this is not a nice way to describe arch linux users (no matter how bad they are, keep being polite) and this should be fixed.

**Comment by fami-com** [comment]
I think that that's your own problems with imagination.

**Comment by jschx** [comment]
ASCII art is hard, ok?

**Comment by wowse** [comment]
@jschx I disagree, you could do arch linux logo way better, look:
![Arch logo](https://cloud.githubusercontent.com/assets/13320742/12917519/bf7e3a6a-ceee-11e5-9389-267584917c95.png)
